### ISSUE TITLE
HIT input

### ISSUE THREAD

**Issue by cerenali** [john-hewitt/scrambled#5]
figure out a nice way to get all the sentences from MTurk's input format into our Javascript stuff. uses ${variable_name} format...probably will end up using '${sentence' + curr_sentence_index + '}' or something

**Comment by john-hewitt** [comment]
Yeah, that's pretty much exactly what it'll end up looking like, I think...

**Comment by cerenali** [comment]
So here's something frustrating....I'm not exactly sure how the parsing is being done, but it doesn't seem to be good with using a (Javascript) variable name for the MTurk variable name; that is, when I hardcode ${sentence0} it works fine, but if I make a new variable mturk_var_name = 'sentence' + curr_sentence_index and do ${mturk_var_name}, it just puts in the string literal.......

any ideas?  :disappointed:

**Comment by cerenali** [comment]
did it! kind of nasty (creating an array with strings "${sentence0}", etc.), but I mean...it works....
